apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lumen-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: lumen
    spec:
      containers:
      - name: lumen-client
        image: akvo/lumen-client:latest
        ports:
        - containerPort: 80
      - name: lumen-backend
        image: akvo/lumen-backend:latest
        ports:
        - containerPort: 3000
        env: add secrects
