language: java

sudo: required

addons:
  hosts:
  - t1.lumen.local
  - auth.lumen.local
  - backend
  - postgres

services:
  - docker

before_install:
  - mkdir ~/.m2
  - mkdir ~/.lein
  - echo "HOST_UID=$(id -u)" >> .env
  - echo "HOST_GID=$(id -g)" >> .env
  - docker pull alekzonder/puppeteer:0.12.0
  - |
      while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do
         echo "Waiting for postgresql to stop for real."
         sudo service postgresql stop;
         sleep 1;
      done

script:
  - ./ci/build.sh
