language: java
sudo: required
services:
- docker
cache:
  directories:
  - $HOME/.m2
  - $HOME/.lein
  - ${HOME}/google-cloud-sdk
before_install:
- openssl aes-256-cbc -K $encrypted_13abf95e958f_key -iv $encrypted_13abf95e958f_iv
  -in ci/gcloud-service-account.json.enc -out ci/gcloud-service-account.json -d
- if [[ ! -d "$HOME/.m2" ]]; then mkdir "$HOME/.m2"; fi;
- if [[ ! -d "$HOME/.lein" ]]; then mkdir "$HOME/.lein"; fi;
- echo "HOST_UID=$(id -u)" >> .env
- echo "HOST_GID=$(id -g)" >> .env
- if [[ ! -f "${HOME}/google-cloud-sdk/bin/gcloud" ]]; then rm -rf "${HOME}/google-cloud-sdk";
  curl https://sdk.cloud.google.com | bash > /dev/null; fi
script:
- ./ci/rebuild.sh && ./ci/deploy.sh
after_failure:
- PROJECT_NAME=akvo-lumen docker-compose -p akvo-lumen-ci -f docker-compose.yml -f
  docker-compose.ci.yml logs
env:
  global:
  - PATH=${HOME}/google-cloud-sdk/bin:$PATH
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
