language: java

sudo: required

services:
  - docker

before_install:
  - docker pull alekzonder/puppeteer:0.12.0
  - | 
      while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do
         echo "Waiting for postgresql to stop for real."
         sudo service postgresql stop;
         sleep 1;
      done

script:
  - ./ci/build.sh
