language:
  - clojure
  - node_js
sudo: false
before_install:
  - nvm install 4
  - cd client
  - npm config set spin false
  - npm install
  - cd ../backend
script:
  - lein2 do clean, check, test
  - cd ../client
  - npm run lint
  - npm test
