language: java

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.m2
    - $HOME/.lein

before_install:
  - if [[ ! -d "$HOME/.m2" ]]; then mkdir "$HOME/.m2"; fi;
  - if [[ ! -d "$HOME/.lein" ]]; then mkdir "$HOME/.lein"; fi;
  - echo "HOST_UID=$(id -u)" >> .env
  - echo "HOST_GID=$(id -g)" >> .env

script:
  - ./ci/rebuild.sh
