language: java

sudo: required

addons:
  hosts:
  - t1.lumen.local
  - auth.lumen.local
  - backend
  - postgres

services:
  - docker

cache:
  directories:
    - "$HOME/.m2/"
    - "$HOME/.lein/"

before_install:
  - if [[ ! -d "$HOME/.m2" ]]; then mkdir "$HOME/.m2"; fi;
  - if [[ ! -d "$HOME/.lein" ]]; then mkdir "$HOME/.lein"; fi;
  - echo "HOST_UID=$(id -u)" >> .env
  - echo "HOST_GID=$(id -g)" >> .env
  - docker pull alekzonder/puppeteer:0.12.0
  - |
      while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do
         echo "Waiting for postgresql to stop for real."
         sudo service postgresql stop;
         sleep 1;
      done

script:
  - ./ci/build.sh
