version: "3"
services:
 postgres:
   build: postgres
   expose:
    - 5432
 keycloak:
   image: akvo/akvo-keycloak-dev:20181015.be5740a
   expose:
    - 8080
 backend:
   volumes:
      - ./postgres/provision:/pg-certs
   links:
      - keycloak:auth.lumen.local
      - exporter:exporter.lumen.local
   expose:
      - 3000
   environment:
     - HOST_UID
     - HOST_GID
   depends_on:
     - postgres
     - keycloak
     - exporter
 client:
   environment:
     - HOST_UID
     - HOST_GID
 redis:
   image: redis:3.2.9
 windshaft:
   environment:
     - PGSSLROOTCERT=/pg-certs/server.crt
     - LUMEN_ENCRYPTION_KEY=supersecret
   volumes:
      - ./postgres/provision:/pg-certs
 fe-e2e-tests:
   image: akvo/akvo-lumen-e2e-test:20181015.d875262
   volumes:
      - ./client/e2e-test:/app
      - /app/node_modules
   environment:
      - LUMEN_URL=http://t1.lumen.local:3030/
      - LUMEN_USER=jerome
      - LUMEN_PASSWORD=password
   links:
      - keycloak:auth.lumen.local
      - client:t1.lumen.local
   command: "true"
 exporter:
   build: exporter
   expose:
      - 3001
