version: "3"
services:
 postgres:
 keycloak:
 backend:
   image: "eu.gcr.io/${PROJECT_NAME}/lumen-backend:${TRAVIS_COMMIT}"
   environment:
     - WAIT_FOR_DB=true
 client:
   image: "eu.gcr.io/${PROJECT_NAME}/lumen-client:${TRAVIS_COMMIT}"
 redis:
 windshaft:
   image: "eu.gcr.io/${PROJECT_NAME}/lumen-maps:${TRAVIS_COMMIT}"

 backend-functional-tests:
   image: akvo-lumen-backend-dev:develop
   volumes:
      - ./postgres/provision:/pg-certs
      - ./backend:/app
      - ~/.m2:/home/akvo/.m2
      - ~/.lein:/home/akvo/.lein
   environment:
     - HOST_UID
     - HOST_GID
   links:
      - keycloak:auth.lumen.local
   command: "true"