version: "3"
services:
 postgres:
   build: postgres
   ports:
    - "5432:5432"
 keycloak:
   build: keycloak
   ports:
    - "8080:8080"
 backend:
   build:
     context: ./backend
     dockerfile: Dockerfile-dev
   volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
      - ~/.lein:/root/.lein
   links:
      - keycloak:auth.lumen.localhost
   ports:
      - "47480:47480"
      - "3000:3000"
 client:
   build:
     context: ./client
     dockerfile: Dockerfile-dev
   volumes:
      - ./client:/lumen
   ports:
      - "3030:3030"
 redis:
   image: redis:3.2.9
 windshaft:
   build:
     context: ./windshaft
     dockerfile: Dockerfile-dev
   environment:
     - NODE_HEAPDUMP_OPTIONS=nosignal
   volumes:
      - ./windshaft/server:/tiler
      - ./windshaft/config:/config
   ports:
      - "9229:9229"
# statsd-server:
#    image: hopsoft/graphite-statsd
#    expose:
#          - "8125"
#    ports:
#       - 8550:80