version: 2
jobs:
    build:
        docker:
          - image: circleci/clojure‚‚
            environment:
                PROJECT_NAME: akvo-lumen
                PROD_CLUSTER_NAME: lumen
                DEV_CLUSTER_NAME: dev-cluster
                CLOUDSDK_COMPUTE_ZONE: europe-west1-d
                DEBIAN_FRONTEND: noninteractive
                LEIN_FAST_TRAMPOLINE: true
        steps:
          - checkout
          - setup_remote_docker
          - run:
              name: start deps
              command: docker-compose -p lumen-testing -f docker-compose-test.yml up keycloak postgres
          - run:
              name: test backend
              command: docker-compose -p lumen-testing -f docker-compose-test.yml up backend
          - run:
              name: test client
              command: docker-compose -p lumen-testing -f docker-compose-test.yml up client