version: 2
jobs:
    build:
        machine:
            java:
              version: openjdk8
            node:
              version: 5.7.0
            environment:
              PROJECT_NAME: akvo-lumen
              PROD_CLUSTER_NAME: lumen
              DEV_CLUSTER_NAME: dev-cluster
              CLOUDSDK_COMPUTE_ZONE: europe-west1-d
              DEBIAN_FRONTEND: noninteractive
              LEIN_FAST_TRAMPOLINE: true
        steps:
          - checkout
          - run:
              name: Install Docker Compose
              command: |
                set -x
                VER="17.03.0-ce"
                curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
                tar -xz -C /tmp -f /tmp/docker-$VER.tgz
                mv /tmp/docker/* /usr/bin
                curl -L https://github.com/docker/compose/releases/download/1.14.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
                chmod +x /usr/local/bin/docker-compose
          - setup_remote_docker:
                version: 17.05.0-ce
          - run:
             - docker-compose -p lumen-testing -f docker-compose-test.yml up keycloak postgres
             - docker-compose -p lumen-testing -f docker-compose-test.yml up backend
             - docker-compose -p lumen-testing -f docker-compose-test.yml up client