development:
  adapter: postgresql
  encoding: utf8
  database: name
  username: hading
  password: my_db_password
  pool: 5 # not mandatory
  timeout: 5000 # not mandatory
  host: localhost
  port: 5434

test:
  adapter: postgresql
  encoding: unicode
  database: test-postgres_test
  pool: 5
  username: test-postgres (or your username if PostgreSQL installed by Homebrew)
  password:
  host: localhost
  port: 5434
