apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: lumen
  namespace: default
spec:
  tls:
  - hosts:
    - dev.test.akvo-ops.org
    secretName: tls
  rules:
    - host: dev.test.akvo-ops.orwg
      http:
        paths:
        - backend:
            serviceName: lumen
            servicePort: 80
