apiVersion: v1
kind: Pod
metadata:
  name: lumen-backend-debug
  labels:
    name: lumen
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: lumen-backend
    image: akvo/lumen-backend:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 3000
    env:
    - name: LUMEN_KEYCLOAK_URL
      value: https://login.test.akvo-ops.org/auth
    - name: LUMEN_FILE_UPLOAD_PATH
      value: /tmp/akvo/lumen
    - name: LUMEN_DB_URL
      valueFrom:
        secretKeyRef:
          name: lumen
          key: lumen_db_url
    - name: LUMEN_FLOW_REPORT_DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: lumen
          key: lumen_flow_report_database_url
